In [118]:
import torch

# 1 pytorch intro (tensor)

Everything in pytorch is based on Tensor operations.

A tensor can have different dimensions ,so it can be 1d, 2d, or even 3d and higher

scalar, vector, matrix, tensor


In [119]:
x = torch.empty(3) # vector of 3 elements
print(x)
x = torch.empty(2,3) # matrix 2 list of 3 elements
print(x)
x = torch.empty(2,2,3) # 2 list that containe 2 list of 3 elements
print(x)

tensor([5.8952e-37, 0.0000e+00, 5.8037e-37])
tensor([[6.9902e-37, 0.0000e+00, 6.1131e-37],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])
tensor([[[6.1478e-37, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [120]:
x = torch.rand(5, 3) # 5 list of 3 elements(random)
print(x)
torch.zeros(5,3) # 5 list of 3 elements(0)
torch.ones(5,3) # 5 list of 3 elements(1,)


tensor([[0.8315, 0.4810, 0.4465],
        [0.2115, 0.6844, 0.9171],
        [0.5554, 0.9913, 0.3301],
        [0.1091, 0.7622, 0.0841],
        [0.1916, 0.6878, 0.4280]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [121]:
x.size(),x.dtype

(torch.Size([5, 3]), torch.float32)

In [122]:
# specify types, float32 default
print(torch.zeros(5, 3, dtype=torch.float16))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [123]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

# requires_grad argument
This will tell pytorch that it will need to calculate the gradients for this tensor
i.e. this is a variable in your model that you want to optimize

In [124]:
x = torch.tensor([5.5, 3], requires_grad=True)

# operations with pytorch

In [125]:
x=torch.ones(2,2)
y=torch.ones(2,2)
#addition each element x[i,j] + y[i,j]
z=y.add_(x)
#sub each element x[i,j] - y[i,j]
z=y.sub(x)
#mul each element x[i,j] * y[i,j]
z=y.mul(x)
#div each element x[i,j] / y[i,j]
z=y.div(x)

In [126]:
z

tensor([[2., 2.],
        [2., 2.]])

# Slicing

In [127]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1, :2]) # row 1, the first tow columns
print(x[1,1]) # element at 1, 1

tensor([[0.8755, 0.0850, 0.9109],
        [0.4002, 0.9927, 0.1998],
        [0.0863, 0.2828, 0.6171],
        [0.6389, 0.7793, 0.7772],
        [0.8153, 0.1452, 0.4304]])
tensor([0.8755, 0.4002, 0.0863, 0.6389, 0.8153])
tensor([0.4002, 0.9927, 0.1998])
tensor([0.4002, 0.9927])
tensor(0.9927)


# Reshape with torch.view()

In [128]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # if -1 it pytorch will automatically determine the necessary size
print(x,x.size())
print(y,y.size())
print(z,z.size())

tensor([[-0.1098, -0.3228,  0.2463, -0.1777],
        [ 1.2212, -0.3734,  1.3100, -0.4451],
        [-1.5143, -1.2796, -0.2747, -0.6193],
        [-0.8648, -0.5364, -0.2694, -1.6441]]) torch.Size([4, 4])
tensor([-0.1098, -0.3228,  0.2463, -0.1777,  1.2212, -0.3734,  1.3100, -0.4451,
        -1.5143, -1.2796, -0.2747, -0.6193, -0.8648, -0.5364, -0.2694, -1.6441]) torch.Size([16])
tensor([[-0.1098, -0.3228,  0.2463, -0.1777,  1.2212, -0.3734,  1.3100, -0.4451],
        [-1.5143, -1.2796, -0.2747, -0.6193, -0.8648, -0.5364, -0.2694, -1.6441]]) torch.Size([2, 8])


# Converting a Torch Tensor to a NumPy array and vice versa

In [129]:
a=torch.ones(2,2)
b = a.numpy()
print(b)
print(type(b))
# If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


# numpy to torch with .from_numpy(x)

In [130]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# 2 auto grad and using optemizer

The autograd package provides automatic differentiation for all operations on Tensors

In [146]:
# requires_grad = True -> tracks all operations on the tensor (x). 
x = torch.zeros(3,5, requires_grad=True)
y =  x +2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], grad_fn=<AddBackward0>)


Let's compute the gradients with backpropagation
When we finish our computation we can call .backward() and have all the gradients computed automatically.
The gradient for this tensor will be accumulated into .grad attribute.
It is the partial derivate of the function w.r.t. the tensor

In [148]:
z=y*y
print(z)
z=z.mean()
print(z)

z.backward()
print(x.grad) # dz/dx
# Generally speaking, torch.autograd is an engine for computing vector-Jacobian product
# It computes partial derivates while applying the chain rule

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]], grad_fn=<MulBackward0>)
tensor(4., grad_fn=<MeanBackward0>)
tensor([[0.5333, 0.5333, 0.5333, 0.5333, 0.5333],
        [0.5333, 0.5333, 0.5333, 0.5333, 0.5333],
        [0.5333, 0.5333, 0.5333, 0.5333, 0.5333]])


In [154]:
# Model with non-scalar output:
x = torch.ones(3, requires_grad=True)
y = x * 2
for _ in range(2):
    y = y * 2
print(y)
print(y.shape)

# If a Tensor is non-scalar (more than 1 elements), we need to specify arguments for backward() 
# specify a gradient argument that is a tensor of matching shape.

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([8., 8., 8.], grad_fn=<MulBackward0>)
torch.Size([3])
tensor([8.0000e-01, 8.0000e+00, 8.0000e-04])


In [156]:
# Stop a tensor from tracking history
# For example during our training loop when we want to update our weights
# then this update operation should not be part of the gradient computation
a = torch.randn(2, 2)

print(a.requires_grad)
b = ((a * 3) / (a - 1))
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [158]:
# get a new Tensor with the same content but no gradient computation:
# wrap in 'with torch.no_grad():'
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print(x)
    print((x ** 2).requires_grad)

True
tensor([1., 1., 1.], requires_grad=True)
False


# backward() accumulates the gradient for this tensor into .grad attribute.
# !!! We need to be careful during optimization !!!
# Use .zero_() to empty the gradients before a new optimization step!

In [165]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()
    
    print(weights)

    # optimize model, i.e. adjust weights...
    with torch.no_grad():
        weights -= 0.1 * weights.grad

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([0.7000, 0.7000, 0.7000, 0.7000], requires_grad=True)
tensor([0.4000, 0.4000, 0.4000, 0.4000], requires_grad=True)
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)


# 3 backpropagation

loss tensor(1., grad_fn=<PowBackward0>)
w.grad tensor(-2.)
w now:  tensor(1.0200, requires_grad=True)


# Gradient Descent

In [170]:
# gradientdescent manually
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.dot(2*x, y_pred - y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 3: w = 1.872, loss = 0.76800019
epoch 5: w = 1.980, loss = 0.01966083
epoch 7: w = 1.997, loss = 0.00050331
epoch 9: w = 1.999, loss = 0.00001288
epoch 11: w = 2.000, loss = 0.00000033
epoch 13: w = 2.000, loss = 0.00000001
epoch 15: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [176]:
# gradientdescent auto
# Linear regression
# f = w * x 

# here : f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

print(f'Prediction before training: f(5) = {forward(5).item():.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    #w.data = w.data - learning_rate * w.grad
    with torch.no_grad():
        w -= learning_rate * w.grad
    
    # zero the gradients after updating
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {forward(5).item():.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000
